### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by Itswali** [Itswali/catalog-of-my-thing#19]
Hi, We are a team of 3 members @Itswali  @PierreBarba  and @ONJoseph 

Team Member - 1 @Itswali .
Team Member - 2 @PierreBarba.
Team Member - 3 @ONJoseph.
[Link](https://github.com/Itswali/catalog-of-my-thing/projects/1) to the project

**Comment by GzimAsani** [comment]
### Hello, @Itswali , @ONJoseph  and @PierreBarba            :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with tasks and board :+1: 

 ## Required Changes 

- [ ] Check the comments below at the end of this file :arrow_double_down: 
- [ ] Each of the team members has some missing, merged bullet points together. Kindly be reminded that each of the bullet points should have a corresponding task on the board, below you have some examples but please double-check and add tasks on the board for each of them.

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._









### **---------------------------------------------------------------------------Comments---------------------------------------------------------------------**



- [x] All the group tasks must have a corresponding task on the board, also they will look better if assigned to all team members ![image](https://user-images.githubusercontent.com/62705947/227971388-881624ee-fe01-42d9-a6ae-5cac3d7a5e67.png)
- [x] Each bullet point should have its own corresponding card on the board, currently, you have merged 2 bullet points in one card like these two
![image](https://user-images.githubusercontent.com/62705947/227972053-e6f5613a-f4e6-4346-9c69-f474498871e2.png)
- [x] I can't find a card for this requirement ![image](https://user-images.githubusercontent.com/62705947/227972652-e8ce73f7-dc74-423b-a1f6-4e7bbeb1c5a4.png)
- [x] Team member one should have cards for the following requests bullet points as well, they need to be descriptive similar to the bullet points 
![image](https://user-images.githubusercontent.com/62705947/227973253-9ca0bd5a-2358-42fa-a5ce-59afe6f72c1a.png)

**Comment by mckent05** [comment]
Hi team, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to start working on your capstone :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- You have set up your Kanban board properly, well done 👏 👏 

## Optional suggestions
- Please replace all project descriptions, where you have used images, with texts

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Itswali** [comment]
Thanks for the Review
